name: miss_hit

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**.m'
      - '.github/workflows/miss_hit.yml'
  pull_request:
    branches: ['*']
    paths:
      - '**.m'
      - '.github/workflows/miss_hit.yml'
jobs:

  miss_hit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        command: ["mh_style", "mh_metric --ci && mh_lint"]
      fail-fast: true  # cancel all jobs if one fails

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install -r requirements.txt

    - name: ${{ matrix.command }}
      run: |
        ${{ matrix.command }}
